# Generated by Django 4.2.7 on 2024-09-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp4', '0002_alter_users_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='balance',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
