# Generated by Django 4.2.7 on 2024-09-22 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp4', '0005_histori'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='histori',
            new_name='historie',
        ),
    ]
