# Generated by Django 4.2.7 on 2024-09-23 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp4', '0010_users_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historie',
            name='users',
        ),
        migrations.RemoveField(
            model_name='users',
            name='history',
        ),
        migrations.AddField(
            model_name='historie',
            name='history',
            field=models.TextField(default='no trasaction yet'),
        ),
        migrations.AddField(
            model_name='users',
            name='users',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vtuapp4.historie'),
        ),
    ]
