# Generated by Django 4.2.7 on 2024-09-23 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp4', '0011_remove_historie_users_remove_users_history_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='users',
            new_name='userss',
        ),
    ]
