# Generated by Django 4.2.7 on 2024-09-24 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp4', '0016_alter_historie_options_alter_historie_userss'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historie',
            options={'ordering': ['userss'], 'verbose_name_plural': 'use'},
        ),
        migrations.AlterField(
            model_name='historie',
            name='userss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='use'),
        ),
    ]
