# Generated by Django 4.2.7 on 2024-09-27 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp4', '0017_alter_historie_options_alter_historie_userss'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historie',
            options={'ordering': ['userss'], 'verbose_name_plural': 'history'},
        ),
    ]
