# Generated by Django 4.2.7 on 2024-09-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp4', '0018_alter_historie_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='historie',
            options={'verbose_name_plural': 'history'},
        ),
    ]
