# Generated by Django 4.2.7 on 2024-09-27 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp4', '0019_transaction_alter_historie_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='transaction',
        ),
    ]
