# Generated by Django 4.2.7 on 2024-09-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp4', '0020_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='historie',
            name='date',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
