# Generated by Django 4.2.7 on 2024-09-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp4', '0024_alter_historie_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historie',
            name='dates',
            field=models.DateTimeField(auto_created=True, default=None, null=True),
        ),
    ]
