# Generated by Django 4.2.7 on 2024-10-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp4', '0027_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='purchase_total',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
